# Generated by Django 3.1.4 on 2021-04-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
